
# Project name.
name: 'dbt_meta_testing'
version: '0.2.0'
config-version: 2
require-dbt-version: ">=0.19.0"

# The "profile" dbt uses for this project.
profile: 'dbt_meta_testing'

# Configuration paths.
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         
    - "target"
    - "dbt_modules"

# Configured for the dbt_meta_testing.logger macro.
vars:
    logging_level: INFO
